#! /bin/sh

sxhkd &
picom &
wal -R
. "${HOME}/.cache/wal/colors.sh"
dunst \
	-lb "${color0}" \
	-nb "${color1}" \
	-cb "${color3}" \
	-lf "${color7}" \
	-bf "${color7}" \
	-cf "${color7}" \
	-nf "${color7}" &
conky & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Pqiv border=off
